import { StyleSheet } from 'react-native';
import { color } from '@/assets';

/**
 * Auto-generated shared StyleSheet.
 *
 * Holds style objects that are identical across two or more screens so each
 * object is declared exactly once instead of being repeated per screen. Screens
 * reference these via `sharedStyles.<key>`. Generated by the shared-style
 * hoisting pass — do not edit by hand.
 */
export const sharedStyles = StyleSheet.create({
  container: {
    height: '100%',
    width: '100%',
    backgroundColor: color.surface.default,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  container2: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  title: { fontSize: 18, fontWeight: '600' },
  subtitle: { marginTop: 8, opacity: 0.6 },
});
